networks:
  envoy:
    driver: bridge
    name: envoy

services:
  api-gateway:
    image: envoyproxy/envoy:v1.23-latest
    container_name: api-gateway
    networks:
      - envoy
    volumes:
      - ./ApiGateways/Envoy/config:/etc/envoy
    ports:
      - "8080:8080"
      - "8001:8001"
    depends_on:
      - example-api

  example-api:
    image: hexsorcerer/example-api
    container_name: example-api
    networks:
      - envoy
    expose:
      - "80"
    build:
      context: .
      dockerfile: Services/Example/Example.API/Dockerfile
